"""Render the bash wrapper script that invokes real claude with hooks."""

from __future__ import annotations

import json

WRAPPER_TEMPLATE = r"""#!/usr/bin/env bash
# claude-tap wrapper — injects hooks when CLAUDE_TAP_ACTIVE=1.
# DO NOT EDIT — regenerated by `claude-tap install`.

set -e

# 1. Find real claude (skip self).
SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
find_real_claude() {
    local IFS=:
    for d in $PATH; do
        [[ "$d" == "$SELF_DIR" ]] && continue
        [[ -x "$d/claude" ]] && printf '%s' "$d/claude" && return 0
    done
    return 1
}

REAL_CLAUDE="$(find_real_claude)" || { echo "claude not found in PATH" >&2; exit 127; }

# 2. Passthrough conditions.
if [[ "${CLAUDE_TAP_ACTIVE:-}" != "1" ]] || [[ "${CLAUDE_TAP_DISABLED:-}" == "1" ]]; then
    exec "$REAL_CLAUDE" "$@"
fi

# 3. Pass through subcommands that don't accept --session-id / --settings.
case "${1:-}" in
    mcp|config|api-key|--version|-v|--help|-h)
        exec "$REAL_CLAUDE" "$@"
        ;;
esac

# 4. Tmux detection.
if [[ -n "${TMUX_PANE:-}" ]] && command -v tmux >/dev/null 2>&1; then
    INFO=$(tmux display-message -t "$TMUX_PANE" -p '#{session_name}|#{window_id}' 2>/dev/null || true)
    if [[ -n "$INFO" ]]; then
        export CLAUDE_TAP_TMUX_SESSION_NAME="${INFO%%|*}"
        export CLAUDE_TAP_TMUX_WINDOW_ID="${INFO#*|}"
        export CLAUDE_TAP_TMUX_PANE_ID="$TMUX_PANE"
    fi
fi

# 5. Skip --session-id injection if user already passed one.
SKIP_SESSION_ID=false
for arg in "$@"; do
    case "$arg" in
        --resume|--resume=*|-r|--session-id|--session-id=*|--continue|-c)
            SKIP_SESSION_ID=true
            break
            ;;
    esac
done

# 6. Settings JSON with all 8 hooks (rendered at install time).
HOOKS_JSON='__HOOKS_JSON__'

# 7. Exec real claude with injected flags.
if $SKIP_SESSION_ID; then
    exec "$REAL_CLAUDE" --settings "$HOOKS_JSON" "$@"
elif command -v uuidgen >/dev/null 2>&1; then
    SID=$(uuidgen | tr '[:upper:]' '[:lower:]')
    exec "$REAL_CLAUDE" --session-id "$SID" --settings "$HOOKS_JSON" "$@"
else
    # uuidgen unavailable → skip session-id injection but keep settings.
    exec "$REAL_CLAUDE" --settings "$HOOKS_JSON" "$@"
fi
"""

# Per-event timeouts. PermissionRequest is sync, so its timeout must be
# slightly larger than CLAUDE_TAP_DECISION_TIMEOUT (default 120) so that
# claude-tap times out cleanly before claude SIGKILLs the hook.
_TIMEOUTS = {
    "SessionStart": 10,
    "UserPromptSubmit": 10,
    "PreToolUse": 10,
    "PostToolUse": 10,
    "Notification": 10,
    "Stop": 10,
    "SessionEnd": 2,
    "PermissionRequest": 125,
}


def build_settings_json() -> dict:
    """Build the --settings JSON payload registering all 8 hooks."""

    def hook_entry(event: str) -> list[dict]:
        return [
            {
                "matcher": "",
                "hooks": [
                    {
                        "type": "command",
                        "command": f"claude-tap-hook {event}",
                        "timeout": _TIMEOUTS[event],
                    }
                ],
            }
        ]

    return {"hooks": {event: hook_entry(event) for event in _TIMEOUTS}}


def render_wrapper() -> str:
    """Render the bash wrapper with the settings JSON inlined."""
    settings = json.dumps(
        build_settings_json(),
        ensure_ascii=False,
        separators=(",", ":"),
    )
    # Escape single quotes to keep it valid inside the bash single-quoted
    # string ('...').
    settings_escaped = settings.replace("'", "'\\''")
    return WRAPPER_TEMPLATE.replace("__HOOKS_JSON__", settings_escaped)
